# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(max_length=50),
        ),
    ]
