# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_log', '0002_carelog_idx_carelog_family_time_and_more'),
        ('family', '0002_family_updated_at'),
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['family', 'status'], name='idx_todo_family_status'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['assignee', 'status'], name='idx_todo_assignee'),
        ),
    ]
