# Generated by Django 6.0.4 on 2026-04-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
