# Generated by Django 5.2.13 on 2026-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('caregiver', 'Caregiver'), ('family_member', 'Family Member'), ('elder', 'Elder')], max_length=20, null=True),
        ),
    ]
