# Generated by Django 6.0.4 on 2026-04-12 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='family.family')),
            ],
            options={
                'db_table': 'health_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlertThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heart_rate_high', models.IntegerField(default=100)),
                ('heart_rate_low', models.IntegerField(default=50)),
                ('blood_oxygen_low', models.DecimalField(decimal_places=1, default=93.0, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_alert_threshold', to='family.family')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_alert_threshold',
            },
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('blood_oxygen', 'Blood Oxygen'), ('step_count', 'Step Count'), ('active_energy', 'Active Energy')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('bpm', 'BPM'), ('%', '%'), ('steps', 'Steps'), ('kcal', 'kcal')], max_length=10)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='family.family')),
            ],
            options={
                'db_table': 'health_data',
                'ordering': ['-recorded_at'],
                'unique_together': {('family', 'type', 'recorded_at')},
            },
        ),
    ]
