# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_updated_at'),
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['family', '-recorded_at'], name='idx_alert_family_time'),
        ),
        migrations.AddIndex(
            model_name='healthdata',
            index=models.Index(fields=['family', 'type', '-recorded_at'], name='idx_health_query'),
        ),
    ]
