# Generated by Django 5.2.14 on 2026-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_expand_health_type_for_blood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='source',
            field=models.CharField(choices=[('apple_watch', 'Apple Watch'), ('iphone', 'iPhone'), ('manual', 'Manual'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
