# Generated by Django 6.0.4 on 2026-04-12 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages_history', models.JSONField(default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FirstAidDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('embedding', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'first_aid_document',
                'ordering': ['title'],
            },
        ),
    ]
