# Generated by Django 6.0.4 on 2026-04-12 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care_log', '0001_initial'),
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_translated', models.JSONField(blank=True, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('weekly', 'Weekly'), ('as_needed', 'As Needed')], max_length=20)),
                ('times', models.JSONField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('instructions_translated', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_medications', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='family.family')),
            ],
            options={
                'db_table': 'medication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField(max_length=500)),
                ('scheduled_time', models.CharField(max_length=5)),
                ('note', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('care_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_confirmations', to='care_log.carelog')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_confirmations', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='medication.medication')),
            ],
            options={
                'db_table': 'medication_confirmation',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
