# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_updated_at'),
        ('medication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['family', 'is_active'], name='idx_med_family_active'),
        ),
    ]
