# Generated by Django 5.2.13 on 2026-04-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_alter_medication_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('thrice_daily', 'Thrice Daily'), ('weekly', 'Weekly'), ('as_needed', 'As Needed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationconfirmation',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
