# Generated by Django 6.0.4 on 2026-04-12 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_translated', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(choices=[('medical', 'Medical'), ('medication', 'Medication'), ('rehab', 'Rehab'), ('leave', 'Leave'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
                ('reminder_minutes', models.IntegerField(default=60)),
                ('note', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('medication', 'Medication'), ('leave', 'Leave')], default='manual', max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='family.family')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['start_time'],
            },
        ),
    ]
