# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0001_initial'),
        ('family', '0002_family_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['family', 'start_time'], name='idx_event_family_time'),
        ),
    ]
