# Generated by Django 6.0.4 on 2026-04-12 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.JSONField(blank=True, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('auto_call_119', models.BooleanField(default=True)),
                ('notified_members', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('resolved', 'Resolved')], default='triggered', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_records', to='family.family')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sos_record',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
