# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardrequest_translation_payloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('withdrawn', 'Withdrawn'),
                    ('completed', 'Completed'),
                ],
                default='pending',
                max_length=10,
            ),
        ),
    ]
