# Generated by Django 5.2.13 on 2026-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_device_device_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('health_alert', 'Health alert'), ('medication_reminder', 'Medication reminder'), ('medication_confirmed', 'Medication confirmed'), ('leave_request', 'Leave request'), ('leave_status', 'Leave status'), ('board_request', 'Board request'), ('board_approved', 'Board approved'), ('expense_scanned', 'Expense scanned'), ('sos', 'SOS'), ('sos_resolved', 'SOS resolved'), ('event_reminder', 'Event reminder'), ('todo_assigned', 'Todo assigned'), ('chat_message', 'Chat message')], max_length=30),
        ),
    ]
