# Generated by Django 6.0.4 on 2026-04-12 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('medication', 'Medication'), ('vital', 'Vital'), ('meal', 'Meal'), ('activity', 'Activity'), ('note', 'Note')], max_length=20)),
                ('content', models.JSONField()),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='family.family')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'care_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
