# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_log', '0001_initial'),
        ('family', '0002_family_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carelog',
            index=models.Index(fields=['family', '-timestamp'], name='idx_carelog_family_time'),
        ),
        migrations.AddIndex(
            model_name='carelog',
            index=models.Index(fields=['family', 'type'], name='idx_carelog_family_type'),
        ),
    ]
