# Generated by Codex for admin dashboard mutation auditing.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMutationAuditLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Create'),
                            ('delete', 'Delete'),
                            ('upload', 'Upload'),
                            ('presign_preview', 'Presign preview'),
                            ('presign_download', 'Presign download'),
                        ],
                        max_length=32,
                    ),
                ),
                ('table', models.CharField(blank=True, max_length=64, null=True)),
                ('record_id', models.CharField(blank=True, max_length=64, null=True)),
                ('bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('object_key', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='admin_mutation_audit_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'admin_mutation_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminmutationauditlog',
            index=models.Index(
                fields=['table', 'record_id'],
                name='idx_admin_audit_record',
            ),
        ),
        migrations.AddIndex(
            model_name='adminmutationauditlog',
            index=models.Index(
                fields=['action', '-created_at'],
                name='idx_admin_audit_action',
            ),
        ),
    ]
