# Generated by Codex for admin dashboard request monitoring.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequestLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'request_id',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_request_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminrequestlog',
            index=models.Index(fields=['-created_at'], name='idx_admin_req_created'),
        ),
        migrations.AddIndex(
            model_name='adminrequestlog',
            index=models.Index(
                fields=['method', '-created_at'],
                name='idx_admin_req_method',
            ),
        ),
        migrations.AddIndex(
            model_name='adminrequestlog',
            index=models.Index(
                fields=['status_code', '-created_at'],
                name='idx_admin_req_status',
            ),
        ),
        migrations.AddIndex(
            model_name='adminrequestlog',
            index=models.Index(
                fields=['user_email', '-created_at'],
                name='idx_admin_req_user',
            ),
        ),
    ]
