# Generated by Codex for admin dashboard record updates.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_api', '0002_admin_request_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmutationauditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('create', 'Create'),
                    ('update', 'Update'),
                    ('delete', 'Delete'),
                    ('upload', 'Upload'),
                    ('presign_preview', 'Presign preview'),
                    ('presign_download', 'Presign download'),
                ],
                max_length=32,
            ),
        ),
    ]