# Generated by Django 5.2.13 on 2026-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_idx_messages_chat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('purchase_request', 'Purchase Request'), ('leave_request', 'Leave Request')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
