# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('family', '0002_family_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['family', '-date'], name='idx_expense_family_date'),
        ),
    ]
