# Generated by Django 5.2.13 on 2026-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_idx_expense_family_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deid_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expense',
            name='deid_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='deid_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='raw_image_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='redacted_image_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
