# Generated by Django 6.0.4 on 2026-04-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0002_event_idx_event_family_time'),
        ('family', '0002_family_updated_at'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['family', 'status'], name='idx_leave_family_status'),
        ),
    ]
