# Generated by Django 5.2.13 on 2026-04-29 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_idx_leave_family_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='leave.leave')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_vote',
                'ordering': ['voted_at'],
                'unique_together': {('leave', 'member')},
            },
        ),
    ]
