# Generated by Django 6.0.4 on 2026-04-12 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('elder_name', models.CharField(max_length=100)),
                ('elder_birth_date', models.DateField(blank=True, null=True)),
                ('invite_code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'families',
                'db_table': 'family',
                'ordering': ['-created_at'],
            },
        ),
    ]
