# Generated by Django 5.2.13 on 2026-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='invite_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
